const commentActionTypes = {
  GET_COMMENTS_BEGIN: 'GET_COMMENTS_BEGIN',
  GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
  GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',
  CREATE_COMMENT_BEGIN: 'CREATE_COMMENT_BEGIN',
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_FAILURE: 'CREATE_COMMENT_FAILURE'
};
export default commentActionTypes;
