const meetupActionTypes = {
  GET_MEETUPS_BEGIN: 'GET_MEETUPS_BEGIN',
  GET_MEETUPS_SUCCESS: 'GET_MEETUPS_SUCCESS',
  GET_MEETUPS_FAILURE: 'GET_MEETUPS_FAILURE',
  GET_MEETUP_BEGIN: 'GET_MEETUP_BEGIN',
  GET_MEETUP_SUCCESS: 'GET_MEETUP_SUCCESS',
  GET_MEETUP_FAILURE: 'GET_MEETUP_FAILURE',
};
export default meetupActionTypes;
