const questionActionTypes = {
  GET_QUESTION_BEGIN: 'GET_QUESTION_BEGIN',
  GET_QUESTION_SUCCESS: 'GET_QUESTION_SUCCESS',
  GET_QUESTION_FAILURE: 'GET_QUESTION_FAILURE',
  ASK_QUESTION_BEGIN: 'ASK_QUESTION_BEGIN',
  ASK_QUESTION_SUCCESS: 'ASK_QUESTION_SUCCESS',
  ASK_QUESTION_FAILURE: 'ASK_QUESTION_FAILURE'
};
export default questionActionTypes;
